language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0

before_install:
 - gem install bundler:2.2.11


script:
 - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
 - sudo apt-get -y install nodejs
 - bundle exec rspec

deploy:
        provider: heroku
        api_key: 3bd9e2fc-3d9b-4ddf-bd9d-7055ea2195c2
        app: enigmatic-lowlands-74328
        run: "rake db:migrate"
        on:
                all_branches: true
   
